name: Generate

on:
  push:
    branches: [ main ]
#   schedule:
#     - cron:  '* * * * 1'

jobs:
  generate:
    permissions:
       contents: write
       pull-requests: write
    runs-on: ubuntu-latest
    env:
      # the version of deno used by Run on Slack (v1.31.1)
      deno-version: v1.31.1
      BRANCH_NAME: generate_$(date +"%Y-%m-%d_%H:%")

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno ${{ env.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.deno-version }}

      - name: Run generation script
        run: ./scripts/generate

      - name: Setup Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Commit changes
        run: |
           git checkout -b $BRANCH_NAME
           git commit -a -m "Changes "
           git push --set-upstream origin new-branch
        env:
           GH_TOKEN: ${{ github.token }}

      - name: Create PR
        run: gh pr create --title "New generated changes" --body "Everything works again"
        env:
           GH_TOKEN: ${{ github.token }}
