name: Generate

on:
  push:
    branches: [ main ]
#   schedule:
#     - cron:  '* * * * 1'

jobs:
  generate:
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    env:
      # the version of deno used by Run on Slack (v1.31.1)
      deno-version: v1.31.1

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno ${{ env.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.deno-version }}
      
      - name: Setup Git config
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: Set BRANCH_NAME
        run: echo "BRANCH_NAME=generate_$(date +"%Y-%m-%d_%H:%")" >> $GITHUB_ENV

      - name: Run generation script
        run: ./scripts/generate
      
      - name: Commit changes
        continue-on-error: true
        run: |
            git checkout -b $BRANCH_NAME
            git commit -a -m "Latest generated changes"

      - name: Create Pull Request
        if: ${{ success() }}
        run: |
            git push --set-upstream origin $BRANCH_NAME
            gh pr create --fill
        env:
           GH_TOKEN: ${{ github.token }}
